-- MySQL Script generated by MySQL Workbench
-- Qua 21 Jun 2017 19:04:47 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escolar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escolar` ;

-- -----------------------------------------------------
-- Schema escolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escolar` DEFAULT CHARACTER SET utf8 ;
USE `escolar` ;

-- -----------------------------------------------------
-- Table `escolar`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escolar`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `escolar`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idAluno`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolar`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escolar`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `escolar`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idAluno`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolar`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escolar`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `escolar`.`Disciplina` (
  `idDisciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolar`.`Boletim`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escolar`.`Boletim` ;

CREATE TABLE IF NOT EXISTS `escolar`.`Boletim` (
  `Aluno_idAluno` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `testeB1` DOUBLE NULL,
  `provaB1` DOUBLE NULL,
  `testeB2` DOUBLE NULL,
  `provaB2` DOUBLE NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Disciplina_idDisciplina`),
  INDEX `fk_Boletim_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Boletim_Disciplina2_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Boletim_Aluno`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `escolar`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boletim_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `escolar`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
