/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoController;
import java.util.Observable;
import java.util.Observer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evson
 */
public class PanelListAlunos extends javax.swing.JPanel implements Observer {
    /**
     * Creates new form PanelListAlunos
     */
    public PanelListAlunos() {
        initComponents();
        tabelaAlunos.setModel(new DefaultTableModel(AlunoController.getInstance().getAlunosObjects(), AlunoController.getNomeColunas()));
        AlunoController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();

        setName("body"); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 325));

        scrollPane.setPreferredSize(new java.awt.Dimension(660, 315));

        tabelaAlunos.setModel(tabelaAlunos.getModel());
        tabelaAlunos.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelaAlunos.setName("tabela"); // NOI18N
        tabelaAlunos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tabelaAlunos);
        if (tabelaAlunos.getColumnModel().getColumnCount() > 0) {
            tabelaAlunos.getColumnModel().getColumn(0).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(0).setHeaderValue("ID");
            tabelaAlunos.getColumnModel().getColumn(1).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(1).setHeaderValue("Nome");
            tabelaAlunos.getColumnModel().getColumn(2).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(2).setHeaderValue("Matrícula");
            tabelaAlunos.getColumnModel().getColumn(3).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(3).setHeaderValue("Boletins");
            tabelaAlunos.getColumnModel().getColumn(4).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(4).setHeaderValue("Editar");
            tabelaAlunos.getColumnModel().getColumn(5).setResizable(false);
            tabelaAlunos.getColumnModel().getColumn(5).setHeaderValue("Deletar");
        }

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaAlunos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        DefaultTableModel table = (DefaultTableModel) tabelaAlunos.getModel();
        table.addRow(AlunoController.getInstance().getAlunoObject(arg));
    }
}
