/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DisciplinaController;
import java.util.Observable;
import java.util.Observer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evson
 */
public class PanelListDisciplinas extends javax.swing.JPanel implements Observer{
    /**
     * Creates new form PanelListDisciplinas
     */
    public PanelListDisciplinas() {
        initComponents();
        tabelaDisciplinas.setModel(new DefaultTableModel(DisciplinaController.getInstance().getDisciplinasObjects(), DisciplinaController.getNomeColunas()));
        DisciplinaController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabelaDisciplinas = new javax.swing.JTable();

        setToolTipText("");
        setName("body"); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 325));

        scrollPane.setPreferredSize(new java.awt.Dimension(660, 315));

        tabelaDisciplinas.setModel(tabelaDisciplinas.getModel());
        tabelaDisciplinas.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tabelaDisciplinas.setName("tabela"); // NOI18N
        tabelaDisciplinas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaDisciplinas.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tabelaDisciplinas);
        if (tabelaDisciplinas.getColumnModel().getColumnCount() > 0) {
            tabelaDisciplinas.getColumnModel().getColumn(0).setResizable(false);
            tabelaDisciplinas.getColumnModel().getColumn(1).setResizable(false);
            tabelaDisciplinas.getColumnModel().getColumn(2).setResizable(false);
            tabelaDisciplinas.getColumnModel().getColumn(3).setResizable(false);
            tabelaDisciplinas.getColumnModel().getColumn(4).setResizable(false);
        }

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaDisciplinas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        DefaultTableModel table = (DefaultTableModel) tabelaDisciplinas.getModel();
        table.addRow(DisciplinaController.getInstance().getDisciplinaObject(arg));
    }
}
