/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.SwingComponents;
import design.factory.JPanelFactory;
import java.awt.Container;

/**
 *
 * @author evson
 */
public class PanelMenu extends javax.swing.JPanel {
    private boolean vAlunos = false;
    private boolean vBoletins = false;
    private boolean vDisciplinas = false;
    private FrameAlunos frameAlunos;
    private FrameBoletins frameBoletins;
    private FrameDisciplinas frameDisciplinas;
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        visualizarAlunos = new javax.swing.JToggleButton();
        visualizarBoletins = new javax.swing.JToggleButton();
        visualizarDisciplinas = new javax.swing.JToggleButton();
        adicionarAluno = new javax.swing.JButton();
        adicionarBoletim = new javax.swing.JButton();
        adicionarDisciplina = new javax.swing.JButton();
        alterarAluno = new javax.swing.JButton();
        alterarBoletim = new javax.swing.JButton();
        alterarDisciplina = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));
        setName("body"); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 325));
        setLayout(new java.awt.GridBagLayout());

        visualizarAlunos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        visualizarAlunos.setText("Alunos");
        visualizarAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visualizarAlunos.setMaximumSize(new java.awt.Dimension(235, 40));
        visualizarAlunos.setMinimumSize(new java.awt.Dimension(235, 40));
        visualizarAlunos.setPreferredSize(new java.awt.Dimension(210, 40));
        visualizarAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizarAlunosMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(visualizarAlunos, gridBagConstraints);

        visualizarBoletins.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        visualizarBoletins.setText("Boletins");
        visualizarBoletins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visualizarBoletins.setPreferredSize(new java.awt.Dimension(210, 40));
        visualizarBoletins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizarBoletinsMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(visualizarBoletins, gridBagConstraints);

        visualizarDisciplinas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        visualizarDisciplinas.setText("Disciplinas");
        visualizarDisciplinas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visualizarDisciplinas.setMaximumSize(new java.awt.Dimension(235, 40));
        visualizarDisciplinas.setMinimumSize(new java.awt.Dimension(235, 40));
        visualizarDisciplinas.setPreferredSize(new java.awt.Dimension(210, 40));
        visualizarDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizarDisciplinasMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(visualizarDisciplinas, gridBagConstraints);

        adicionarAluno.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        adicionarAluno.setText("Adicionar Aluno");
        adicionarAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarAluno.setMaximumSize(new java.awt.Dimension(235, 40));
        adicionarAluno.setMinimumSize(new java.awt.Dimension(235, 40));
        adicionarAluno.setPreferredSize(new java.awt.Dimension(210, 40));
        adicionarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarAlunoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(adicionarAluno, gridBagConstraints);

        adicionarBoletim.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        adicionarBoletim.setText("Adicionar Boletim");
        adicionarBoletim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarBoletim.setPreferredSize(new java.awt.Dimension(210, 40));
        adicionarBoletim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarBoletimMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(adicionarBoletim, gridBagConstraints);

        adicionarDisciplina.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        adicionarDisciplina.setText("Adicionar Disciplina");
        adicionarDisciplina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarDisciplina.setMaximumSize(new java.awt.Dimension(235, 40));
        adicionarDisciplina.setMinimumSize(new java.awt.Dimension(235, 40));
        adicionarDisciplina.setPreferredSize(new java.awt.Dimension(210, 40));
        adicionarDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarDisciplinaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(adicionarDisciplina, gridBagConstraints);

        alterarAluno.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        alterarAluno.setText("Alterar Aluno");
        alterarAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarAluno.setPreferredSize(new java.awt.Dimension(210, 40));
        alterarAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarAlunoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(alterarAluno, gridBagConstraints);

        alterarBoletim.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        alterarBoletim.setText("Alterar Boletim");
        alterarBoletim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarBoletim.setPreferredSize(new java.awt.Dimension(210, 40));
        alterarBoletim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarBoletimMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(alterarBoletim, gridBagConstraints);

        alterarDisciplina.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        alterarDisciplina.setText("Alterar Disciplina");
        alterarDisciplina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarDisciplina.setPreferredSize(new java.awt.Dimension(210, 40));
        alterarDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarDisciplinaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(alterarDisciplina, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarAlunosMouseClicked
        // TODO add your handling code here:
        vAlunos = !vAlunos;
        if (vAlunos) {
            frameAlunos = new FrameAlunos();
            frameAlunos.setVisible(true);
        }
        else {
            frameAlunos.setVisible(false);
            frameAlunos.dispose();
        }
    }//GEN-LAST:event_visualizarAlunosMouseClicked

    private void visualizarDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarDisciplinasMouseClicked
        // TODO add your handling code here:
        vDisciplinas = !vDisciplinas;
        if (vDisciplinas) {
            frameDisciplinas = new FrameDisciplinas();
            frameDisciplinas.setVisible(true);
        }
        else {
            frameDisciplinas.setVisible(false);
            frameDisciplinas.dispose();
        }
    }//GEN-LAST:event_visualizarDisciplinasMouseClicked

    private void adicionarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarAlunoMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("adicionarAluno")));
        parent.setVisible(true);
    }//GEN-LAST:event_adicionarAlunoMouseClicked

    private void adicionarDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarDisciplinaMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("adicionarDisciplina")));
        parent.setVisible(true);
    }//GEN-LAST:event_adicionarDisciplinaMouseClicked

    private void visualizarBoletinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarBoletinsMouseClicked
        // TODO add your handling code here:
        vBoletins = !vBoletins;
        if (vBoletins) {
            frameBoletins = new FrameBoletins();
            frameBoletins.setVisible(true);
        }
        else {
            frameBoletins.setVisible(false);
            frameBoletins.dispose();
        }
    }//GEN-LAST:event_visualizarBoletinsMouseClicked

    private void adicionarBoletimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarBoletimMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("adicionarBoletim")));
        parent.setVisible(true);
    }//GEN-LAST:event_adicionarBoletimMouseClicked

    private void alterarAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarAlunoMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("alterarAluno")));
        parent.setVisible(true);
    }//GEN-LAST:event_alterarAlunoMouseClicked

    private void alterarBoletimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarBoletimMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("alterarBoletim")));
        parent.setVisible(true);
    }//GEN-LAST:event_alterarBoletimMouseClicked

    private void alterarDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarDisciplinaMouseClicked
        // TODO add your handling code here:
        Container parent = getParent();
        parent.setVisible(false);
        parent.remove(this);
        parent.add(SwingComponents.setPainelBody(JPanelFactory.getPanel("alterarDisciplina")));
        parent.setVisible(true);
    }//GEN-LAST:event_alterarDisciplinaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAluno;
    private javax.swing.JButton adicionarBoletim;
    private javax.swing.JButton adicionarDisciplina;
    private javax.swing.JButton alterarAluno;
    private javax.swing.JButton alterarBoletim;
    private javax.swing.JButton alterarDisciplina;
    private javax.swing.JToggleButton visualizarAlunos;
    private javax.swing.JToggleButton visualizarBoletins;
    private javax.swing.JToggleButton visualizarDisciplinas;
    // End of variables declaration//GEN-END:variables
}
