/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BoletimController;
import java.util.Observable;
import java.util.Observer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evson
 */
public class PanelListBoletins extends javax.swing.JPanel implements Observer {
    /**
     * Creates new form PanelListBoletins
     */
    public PanelListBoletins() {
        initComponents();
        tabelaBoletins.setModel(new DefaultTableModel(BoletimController.getInstance().getBoletinsObjects(), BoletimController.getNomeColunas()));
        BoletimController.getInstance().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tabelaBoletins = new javax.swing.JTable();

        setName("body"); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 325));

        scrollPane.setPreferredSize(new java.awt.Dimension(660, 315));

        tabelaBoletins.setModel(tabelaBoletins.getModel());
        tabelaBoletins.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaBoletins.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tabelaBoletins);
        if (tabelaBoletins.getColumnModel().getColumnCount() > 0) {
            tabelaBoletins.getColumnModel().getColumn(0).setResizable(false);
            tabelaBoletins.getColumnModel().getColumn(1).setResizable(false);
        }

        add(scrollPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabelaBoletins;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        DefaultTableModel table = (DefaultTableModel) tabelaBoletins.getModel();
        table.addRow(BoletimController.getInstance().getBoletimObject(arg));
    }
}
